version: "3"

services:
  # database
  db:
    container_name: postgres_db
    image: postgres:11
    volumes:
      - ../db_django:/var/lib/postgres/data
    networks:
      - cosmetics_universe_net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: c_universe_db
      POSTGRES_PASSWORD: oVETANsoNHEI

  # db admin panel
  pgadmin4:
    container_name: pgadmin
    image: elestio/pgadmin:latest
    networks:
      - cosmetics_universe_net
    restart: always
    depends_on:
      - db
    ports:
      - "8090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 55vlad.boch55@gmail.com
      PGADMIN_DEFAULT_PASSWORD: oVETANsoNHEI
      PGADMIN_LISTEN_PORT: 80
    volumes:
    - ./servers.json:/pgadmin4/servers.json

  # cosmetics universe app
  cosmetics_universe:
    container_name: cosmetics_universe
    depends_on:
      - db
    ports: 
      - 8080:8080
    build: ../
    command: python manage.py runserver 0.0.0.0:8080

    environment:
      DB_USER_NAME: root
      DB_NAME: c_universe_db
      DB_USER_PASSWORD: oVETANsoNHEI
      DB_HOST: db
      DB_PORT: 5432

    networks:
      - cosmetics_universe_net


networks:
  cosmetics_universe_net: