version: "3"

services:
  # Database
  db:
    container_name: mysql_db
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ../db_django:/var/lib/mysql
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: oVETANsoNHEI
      MYSQL_DATABASE: c_universe_db
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: oVETANsoNHEI
    networks:
      - mysql-phpmyadmin

  # cosmetics universe app
  cosmetics_universe:
    container_name: cosmetics_universe
    depends_on:
      - db
    ports: 
      - 8080:8080
    build: ../
    command: python manage.py runserver 0.0.0.0:8080

    environment:
      DB_USER_NAME: root
      DB_NAME: c_universe_db
      DB_USER_PASSWORD: oVETANsoNHEI
      DB_HOST: db
      DB_PORT: 3306

    networks:
      - mysql-phpmyadmin


networks:
  mysql-phpmyadmin: